db.server.url=jdbc:mysql://localhost:3306/
db.name=elibrary
db.username=root
db.password=YOUR_MYSQL_PASSWORD
admin.email=ADMIN_EMAIL
admin.password=ADMIN_PASSSWORD

# DO NOT COMMIT THIS FILE IN THE GITHUB WITH YOUR PASSWORD 